### ISSUE TITLE
2 Factor authentication support on OAuth Flow?

### ISSUE THREAD

**Issue by krackers** [bloomkd46/homebridge-XfinityHome#2]
### Describe The Bug:

Hi there, thanks for this updated fork. I've been looking through the oauth flow, but since it currently just auto-populates the username and password and submits the form, it doesn't seem like it would support two factor authentication flows. Since I believe the oauth form submission only needs to be done once (and afterwards it uses a refresh token), perhaps that link could just be opened in the browser so the user could fill in the form manually.

### To Reproduce:

Account with 2 factor authentication

### Expected behavior:

<>

### Logs:

```shell
<>
```

### Config:

```shell
<>
```

### Node Version:

0

### NPM Version:

0

### Homebridge Version:

0

### Operating System:

Other

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/bloomkd46/homebridge-XfinityHome/blob/main/CODE_OF_CONDUCT.md)

**Comment by bloomkd46** [comment]
They don't require two factor authentication and due to the fact that if you sign in on a device with the same amount it will change the refresh token I figured you would just go into settings and create a custom profile without two factor authentication and dedicate that to homebridge

##
PS 
I have not gotten it to work yet, it gets stuck logging in
